### ISSUE TITLE
Tooltip appears in incorrect location on repeat hover

### ISSUE THREAD

**Issue by jhockett** [ant-design/ant-design#10008]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Ubuntu 17.10, Firefox 59.0.2, react 16.3.1

### Reproduction link
[https://ant.design/components/tooltip/](https://ant.design/components/tooltip/)

### Steps to reproduce
Hover over tooltip, move mouse away, and then  hover over the same tooltip and it should appear at a different location on the page

### What is expected?
Tooltip should appear in the same spot

### What is actually happening?
Tooltip is in the wrong spot

**Comment by yesmeck** [comment]
Fixed, try reinstall node_modules.

**Comment by chillyistkult** [comment]
@yesmeck How can it be fixed when 3.4.1 is the latest version?

**Comment by yesmeck** [comment]
reinstall node_modules

**Comment by chillyistkult** [comment]
The bug is still happening on production as describe. rc-tooltip version 3.7.2 and antd 3.4.1.

**Comment by yesmeck** [comment]
@chillyistkult Plz create a separator issue.

**Comment by chillyistkult** [comment]
@yesmeck There are already 3 or 4 issues open for this bug. I don't know how you are organized internally, but I would rather not open a 5th issue for the same thing.

#10015 
#10010 
#10008

**Comment by afc163** [comment]
@chillysitkult We believe @yesmeck has fixed this problem in https://github.com/react-component/tooltip/commit/cbb567e10c4136341f476f83b6d168673e724313 cause no more problem show in https://ant.design/components/tooltip/ now. If you still run into this problem, please create a new issue by http://new-issue.ant.design/ and provide reproducible demo which maybe still something wrong we missed.

**Comment by madox2** [comment]
Still the issue with `antd@3.5.0` and popover. However when react component is re-rendered, the popover will move to the correct position. So my workaround for now is triggering re-render when tooltip state changes:

```js
visible={this.state.visible}
onVisibleChange={visible => {
  this.setState({ visible })
  setTimeout(() => this.setState({ workaround: Date.now() }, 10)
}}
```

**Comment by afc163** [comment]
@madox2 Check comment above.

**Comment by dumbest** [comment]
@madox2 You might have use image or something that need time to load in Popover's content. So it doesn't know the size of content the first time. You have to set explicit size of content.

**Comment by cainiaokan** [comment]
@dumbest That's not the case. Because the tooltip is positioned in the right place first time.
When you move away and hover on the element again, then it happens.

**Comment by v5zz** [comment]
The bug is still happening on antd3.12.2

**Comment by ojame** [comment]
An alternative to what @madox2 has described but achieves the same thing:

```
this.setState({ visible: true }, () => {
  window.requestAnimationFrame(() => {
    this.forceUpdate();
  });
});
```

**Comment by qykingle** [comment]
我在最新版4.6.5上面也遇到了这个问题，就是显示的时候，明显有二次偏移。涉及的组件有Tooltip,Popover。
