### ISSUE TITLE
The `Row` component will overflow when setting gutter

### ISSUE THREAD

**Issue by zhuchuji** [ant-design/ant-design#10144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
os: mac os 12, browser: chrome 65

### Reproduction link
[https://zhuchuji.github.io/antd-issues/](https://zhuchuji.github.io/antd-issues/)

### Steps to reproduce
1. Layout with `Row` and `Col`
2. Set `gutter` to the `Row`

### What is expected?
The `Row` should not overflow

### What is actually happening?
The `Row` overflows and produces the scrollbar

---
Antd sets `margin-left` and `margin-right` to a negative value on `Row` to compensate the `padding-left` of the first `Col` child and `padding-right` of the last `Col` child, which will make the `Row` box larger than its parent as it's set to `box-sizing: border-box`. Users have to provide a `container` with padding to ensure the `Row` will not overflow, which is a big problem in layout especially in responsive web, because they have to set variables for gutters and calculate it for the padding of the `container`. It's totally inconvenient. If the grid system removes the first column's `padding-left` and the last column's `padding-right`, the `Row` does not need a negative margin any more. Perhaps, it could be fixed by adding a container in `Row`, so that you don't have to detect which column is the first child and which is the last.

**Comment by zhuchuji** [comment]
@ToJen It's responsive. Antd provides `xs`, `sm`, `md`, `lg` grids for different devices layout. But there's a issue with the `Row` component that it will overflow the container if settting `gutter`. `overflow: hidden` is one of the workaround solutions although it's not that elegant.

**Comment by mariogrieco** [comment]
my solution....
a custom Grid Component....using a gutter prop's object so taking control over the overflow adding padding .....papapa...tuntun =>

```
/* let breakPoints = {
  xs: '575.999', //<
  sm: '576px', // >=
  md: '768px', //  >=
  lg: '992px', // >=
  xl: '1200px', // >=
  xxl: '1600px', // >==
} */

@media screen and (max-width: 575.999px) {
 .Grid {
    padding: 0px ${Gutter};
 }
}

@media screen and (min-width: 576px) {
  .Grid {
    padding: 0px ${Gutter}px;
 }
}

........
```

**Comment by matthewlein** [comment]
I think this is solved in other grids. I wrote this SCSS grid generator 5 years ago that solves the issue by using `padding-left` on the cells for the gutter (instead of using both left and right), and negative `margin-left` on the row to offset the gutter. The overflow happens on the left, so you don't get right scrolling overflow (left overflow is ignored by the browser)

example here:
http://matthewlein.github.io/yellowgrid/

**Comment by orlando** [comment]
Here's a decent workaround with CSS:

```css
  .ant-row {
    margin-right: 0 !important;
    margin-left: 0 !important;
  }

  .ant-col:first-chid {
      padding-left: 0 !important;
  }

  .ant-col:last-child {
    padding-right: 0 !important;
  }
```

This removes the margins from the Row component and the padding of the first and last Col

**Comment by anyexinglu** [comment]
> You can add a wrapper with `overflow: hidden` as workaround: https://codesandbox.io/s/oonl1ylnvy
> 
> There is no solution about this problem now.

But, why not omit the margin for the first and last child?

**Comment by TrueMoein** [comment]
> Here's what I think is a better workaround with CSS:
> 
> ```css
> .ant-row {
>   margin-right: 0 !important;
>   margin-left: 0 !important;
> }
> 
> .ant-col:first-child {
>     padding-left: 0 !important;
> }
> 
> .ant-col:last-child {
>   padding-right: 0 !important;
> }
> ```
> 
> This removes the margins from the Row component and the padding of the first and last Col

use this css in main styles.

**Comment by sametweb** [comment]
> Here's what I think is a better workaround with CSS:
> 
> ```css
> .ant-row {
>   margin-right: 0 !important;
>   margin-left: 0 !important;
> }
> 
> .ant-col:first-child {
>     padding-left: 0 !important;
> }
> 
> .ant-col:last-child {
>   padding-right: 0 !important;
> }
> ```
> 
> This removes the margins from the Row component and the padding of the first and last Col

This solution works! But it's a shame that this problem still exists.

**Comment by Gibbo3771** [comment]
Ticket from 2018 and this is still a problem.

Seems like an easy fix that no one has bothered to implement, the above recommend solution works fine with zero side effects.

**Comment by 1Franck** [comment]
Same problem with v4.7.3

**Comment by Parader** [comment]
+1 

running v4.8.0

**Comment by masonlouchart** [comment]
It's still here in v4.11.2

**Comment by freddiehaddad** [comment]
FYI: The CSS option suggested does not work if you using breakpoints for different screen sizes.  You will end up with margins visible on the wrapped rows.  I ended up using the overflow hidden CSS option and setting it on a parent div.

**Comment by freddiehaddad** [comment]
> Here's what I think is a better workaround with CSS:
> 
> ```css
> .ant-row {
>   margin-right: 0 !important;
>   margin-left: 0 !important;
> }
> 
> .ant-col:first-child {
>     padding-left: 0 !important;
> }
> 
> .ant-col:last-child {
>   padding-right: 0 !important;
> }
> ```
> 
> This removes the margins from the Row component and the padding of the first and last Col

This fails when using responsive breakpoints that cause columns to wrap.  Then the middle rows end up with incorrect margins because of the first and last CSS child selectors.  This solution will work perfect however as long as you aren't using responsive breakpoints.

**Comment by danlupascu** [comment]
We're having this issue as well. Any updates?

**Comment by createdbymahmood** [comment]
Same here, V4.16.0

**Comment by sfbjason** [comment]
I resolve this using

.ant-row-flex, .ant-row {
  margin: 0 !important;
}

**Comment by priyankcommits** [comment]
@afc163 Any update on this please ?

**Comment by scottmurphy1111** [comment]
We solved by wrapping Row in a `<section>` with `box-sizing: border-box`

**Comment by cesarnml** [comment]
Still broken in 4.18.3

**Comment by freshgiammi** [comment]
> This fails when using responsive breakpoints that cause columns to wrap. The rows that get created when hitting the various breakpoints (i.e. xs, sm, md, et.c) end up with incorrect margins because of the first and last CSS child selectors. This solution will work perfect however as long as you aren't using responsive breakpoints.

That is correct. I've managed to get around this by disabling the workaround when a helper class is not present. Since I don't have responsive columns in set in all Row/Col elements, I can dynamically set the helper class and turn off the workaround as needed.

```
.ant-row:not(.gutterfix) {
  margin-right: 0 !important;
  margin-left: 0 !important;
}
.ant-col:not(.gutterfix):first-child {
  padding-left: 0 !important;
}
.ant-col:not(.gutterfix):last-child {
  padding-right: 0 !important;
}
```

I'm using the workaround only when my columns are not getting rearranged in multiple rows.
Basically, if I know that by Col elements will span in multiple rows after a certain breakpoint I've selected, I'll add the class dynamically.

In my case `md` will cause my Columns to be reorganized in two rows, so i'll disable the workaround by checking the current breakpoint with [useBreakpoint()](https://ant.design/components/grid/#components-grid-demo-useBreakpoint) and adding the class accordingly (`className={md ? "gutterfix" : ""}`).

Not the prettiest workaround I'll admit, but at least I don't see any other issue with this method.

**Comment by fdv1** [comment]
Got caught by this one as well, would be nice if someone could fix it.

**Comment by danlupascu** [comment]
I came across this problem a while ago, but since then I realized that it's ok that the row overflows because it is meant to be used with the columns, which are aligned perfectly. So if you're having this problem it's most likely because you're using this component wrong.

**Comment by fdv1** [comment]
Thanks Dan, 
Would you mind elaborating on the correct way to use Row then? As far as I am concerned having  Row overflowing is not ok as stated in the original bug report (it causes the display to "float" on some small screens).

**Comment by danlupascu** [comment]
Sure.

1. Rows should have as children only columns, and nothing else (do not nest directly one row in another row)
2. Columns should have as parents only rows (sometimes you can make a mistake by having a column as a child of another column)


If you follow these two rules you shouldn't have any problems.

If you're still having problems maybe you can create a simple demo and I could show you how to fix your problems.

**Comment by danlupascu** [comment]
As I told you before, I had this issue as well and I fixed it by changing my layout. So it's something you can fix as well.

If you have a demo I can take a look, otherwise I can't remember exactly how I did it.

**Comment by fdv1** [comment]
https://stackblitz.com/edit/react-gaswpc?file=index.js

**Comment by danlupascu** [comment]
Yes, I can see that it overflows, but as I said before, that's not a problem. It's not a problem because the Col is compensating for that. Even in your example, the first column is aligned correctly (they're not exceeding the parent container)

**Comment by fdv1** [comment]
Yes but the row does overflow, causing scroll bars to appear needlessly...

**Comment by priyankcommits** [comment]
+1.

more importantly, as shown in the example, what if we need a div that highlights the background color? And it overflows like that ?

**Comment by cesarnml** [comment]
Minimal example of horizontal overflow (which results in visible horizontal scroll bar).

https://stackblitz.com/edit/react-3dvczh?file=index.js

Yes, it's true that wrapping `Row` in a parent div with `overflow-x: hidden` will stop the scroll bar from appearing as suggested by @afc163 , but it would be nice if the library implemented this fix.

**Comment by Harukisatoh** [comment]
> I resolve this using
> 
> .ant-row-flex, .ant-row { margin: 0 !important; }

Thank you, man! That worked for me! I thought it wouldn't work because I'm using responsive breakpoints to adjust my layout, but I haven't found any issue so far.

**Comment by fuhaiwei** [comment]
This problem is not only in<Row>, but also in<Form.Item>.
The official example also has unnecessary scrollbars, when the width is small enough.
When the width is small enough, the 'wrapperCol' should be ignored and the 'offset' should be 0.

![1](https://user-images.githubusercontent.com/8765657/194732660-dc9b96b1-ac8e-407c-9cf8-9f03917c8903.png)

**Comment by huynd0902** [comment]
Any update? Seem still an issue with the latest version

**Comment by momenfc** [comment]
gutter shouldn't  be more than 30 for horizontal

**Comment by vadym-horbach** [comment]
Nested rows are overlapping other columns in the example at https://stackblitz.com/edit/react-gaswpc-fmxjks?file=index.j

**Comment by hcdiekmann** [comment]
Still present in 5.14.2

**Comment by bantawa04** [comment]
Problem exists in List with grid component as well.

**Comment by yao378186268** [comment]
Holy shit，Still present as of today

**Comment by Alt-er** [comment]
天啊，到今天还在

**Comment by StephaneAdeso** [comment]
I just installed Antd (5.24.1) and after working 30 minutes with this library i got this bug. 
This issue was reported in 2018. We are in 2025 !!!! This team is not serious. Will use another component library. 
If after 30 minutes of work i find a bug that is 7 years old and still not fixed, i can't risk to use this library in all my application and find out what else will pop up. Sorry guys, but 7 years for a bug that still exist in a core component is just amazing. And not in the good way.

**Comment by Summer12130** [comment]
shift still present as of today

**Comment by bigmeow** [comment]
What bug? Isn't this a feature?
