### ISSUE TITLE
antd tabs标签页报错了，显示ownerdocument is not defined

### ISSUE THREAD

**Issue by chenxd1996** [ant-design/ant-design#11612]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
mac os 12.04，chrome68.0.3440.84，react 16.04

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
官网文档tabs标签页里就可以看到出错了

### What is expected?
正常运行

### What is actually happening?
报错崩溃

---
麻烦尽快修复

**Comment by dospolov** [comment]
![image](https://user-images.githubusercontent.com/670682/43688142-3096b352-98ec-11e8-94fe-b050a0c5ad06.png)

**Comment by picodoth** [comment]
https://github.com/react-component/tabs/issues/130 actively fixing

**Comment by cike8899** [comment]
Troubleshoot as soon as possible

**Comment by yesmeck** [comment]
Fixed in upstream, try reinstall node_modules.

**Comment by chenxd1996** [comment]
I rolled back antd version to v3.66, the problem is miss, I will upgrade it when this problem solved.

**Comment by afc163** [comment]
@chenxd1996 It is resolved now.

**Comment by chenxd1996** [comment]
@afc163 Good job!

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/43707005-7c149986-9999-11e8-90d8-28422159893d.png)
use `create-react-app`.
execute `yarn run build` `serve -s build`

**Comment by udielenberg** [comment]
the problem is not yet solved

I'm running antd 3.8.3
and I get this:

![image](https://user-images.githubusercontent.com/39482108/45436140-bca67d00-b6ba-11e8-9108-845da1a2c44c.png)

I know it worked fine till today, which means its something new.

**Comment by picodoth** [comment]
@udielenberg can you try to reinstall node_modules?

**Comment by nameliuqi** [comment]
antd@3.9.4 dont work too, build by roadhog

**Comment by udielenberg** [comment]
@nameliuqi 

All of my webpack configuration are custom made.
can I start working with the **roadhog-cli** without override my configurations?

**Comment by nameliuqi** [comment]
> @nameliuqi
> 
> All of my webpack configuration are custom made.
> can I start working with the **roadhog-cli** without override my configurations?

I may replace roadhog by webpack, so you'd better check your config.
