### ISSUE TITLE
Range slider second round handler is unresponsive on first drag

### ISSUE THREAD

**Issue by tylik1** [ant-design/ant-design#12367]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Google Chrome latest version, OSX

### Reproduction link
[https://ant.design/components/slider/](https://ant.design/components/slider/)

### Steps to reproduce
Go to https://ant.design/components/slider/
Drag the first handler from range slider
Try to drag the second handler

### What is expected?
The second handler should drag

### What is actually happening?
The second handler stays on the same place

---
If you try to drag second handler one more time, works as expected

**Comment by zombieJ** [comment]
This has been fixed in `rc-slider@8.6.3`. Remove `node_modules` and reinstall will work.
![kapture 2018-09-24 at 12 25 54](https://user-images.githubusercontent.com/5378891/45937684-06656080-bff5-11e8-82d3-7ba62c3fac8a.gif)

**Comment by afc163** [comment]
The focus state should be preserved after dragging for accessibility.

**Comment by zombieJ** [comment]
Hmmm @afc163,
Since focused element by drag cause the another handle drag not work, maybe should find another way if want to keep the focus.

**Comment by tylik1** [comment]
@zombieJ  have you checked that? I just installed 8.6.5 and it still fails to work. Also it doesn't work on live website.
