### ISSUE TITLE
Theme switching cannot modify colors using fade method

### ISSUE THREAD

**Issue by qizhancheng** [ant-design/ant-design#20079]
![1](https://user-images.githubusercontent.com/22724560/70124093-f93f0980-16ae-11ea-933a-43f85160c651.png)

![2](https://user-images.githubusercontent.com/22724560/70124069-ef1d0b00-16ae-11ea-9a2f-6e41dd513f4a.png)

- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider-cn/](https://ant.design/components/slider-cn/)

### Steps to reproduce
Slider slider input component style

### What is expected?
Hope to modify the color of fade normally

### What is actually happening?
Theme switching cannot modify colors using fade method

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Same problem as #14774 and #16279

**Comment by qizhancheng** [comment]
Allow [antd-theme-generator](https://github.com/mzohaibqc/antd-theme-generator) to disable the use of faded colors during initial compilation

 ```css-less
@slider-handle-color-focus-shadow: ~"fade(@primary-color, 20%)";
@slider-handle-color-focus: ~"tint(@primary-color, 20%)";
@slider-dot-border-color-active: ~"tint(@primary-color, 50%)";

**Comment by mzohaibqc** [comment]
@afc163  @qizhancheng  I just published a fix `antd-theme-generator@1.1.9` for this issue. I tested with `fade(@primary-color, 20%)`. These are not standard color codes so the previous code was not matching such values. Now I added another option for users to add your custom color code matching array of regex which you want to allow. You can do something like

```
const { generateTheme } = require('antd-theme-generator');

const options = {
  themeVariables: ['@primary-color'],
  customColorRegexArray: [/^fade\(.*\)$/], // An array of regex codes to match your custom color variable values so that code can identify that it's a valid color. Make sure your regex does not adds false positives.
}

generateTheme(options).then(less => {
  console.log('Theme generated successfully');
})
.catch(error => {
  console.log('Error', error);
})
```

I hope this will fix the issue.

**Comment by mzohaibqc** [comment]
@afc163   @qizhancheng I just published a fix `antd-theme-generator@1.1.9` for this issue. I tested with `fade(@primary-color, 20%)`. These are not standard color codes so the previous code was not matching such values. Now I added another option for users to add your custom color code matching array of regex which you want to allow. You can do something like

```
const { generateTheme } = require('antd-theme-generator');

const options = {
  themeVariables: ['@primary-color'],
  customColorRegexArray: [/^fade\(.*\)$/], // An array of regex codes to match your custom color variable values so that code can identify that it's a valid color. Make sure your regex does not adds false positives.
}

generateTheme(options).then(less => {
  console.log('Theme generated successfully');
})
.catch(error => {
  console.log('Error', error);
})
```

I hope this will fix the issue.

**Comment by qizhancheng** [comment]
@mzohaibqc  `customColorRegexArray` does not restrict the use of `fade` color for internal conversion of `antd-theme-generator`. The color used for `fade` at [L353](https://github.com/mzohaibqc/antd-theme-generator/blob/66ba1640b086d17d6ba2c07b9c5f4d83bd0f4c35/index.js#L353) has been converted.

Now I use `~` to define colors, such as `@primary-fade-1:  ~"fade (@ primary-color, 10%)";`

**Comment by mzohaibqc** [comment]
@qizhancheng **customColorRegexArray** allows you to add a regex that will allow or restrict the use of color values.

So there is no more issue related to this ?

**Comment by qizhancheng** [comment]
@mzohaibqc  `customColorRegexArray` does not solve this problem, the `fade (@primary-color, 20%) `in `antd-theme-generator` has been converted to 6 hex values.

**Comment by Gfast2** [comment]
Hi @mzohaibqc , big fan of your awesome Project right now! 🌻 

Since I do not have much experience with `less`, and may even not enough background know-how about how the inheritence/overwrite policy of/from it with normal `css` file.

I'd really wanna do such thing with your project: Let a command `npm run color:css` to produce a single css file, that I can comfortably add it into my create-react-app just as with the stock `import 'ant/dist/antd.css'`. 

Is that possible? 😲 , I've investigate some time on it, in order to figuring out what should I do, and I still missing the parts to understand the whole story. ☕️

**Comment by mzohaibqc** [comment]
@Gfast2 Thank you so much for your kind words. I want to know what you want to achieve. Do you just want 1 or 2 themes (different color schemes) that you can choose or you want the ability to update your theme inside your application? If you have scenario 1 then you just need to create a css file from here and import in your project and if you want that in 2nd scenario, try `antd-theme-generator` or `antd-theme-webpack-plugin`.

Also if you are able to generate `color.less`, simply copy the content and run it in some online compiler and the copy your css in some file and import in your project.

I just tried a sample `color.less` from this example view-source:https://antd-live-theme.firebaseapp.com/  and compiled here https://lesstester.com/

**Comment by Gfast2** [comment]
@mzohaibqc , Thanks for you explaination. Right now I only wanna generate a single `css` file that I can simply imported into my targeted project, which using `antd` (No live theme switching).
But what I found missing with `color.less` is that, After compile the `less` into `css`, For example the button I created, is still missing some css class, and looks only "half way" correct. Still don't know what should I deal with it.

My solution right now is to use webpack `lessLoader` to load `color.less` for extra theme config.

**Comment by mzohaibqc** [comment]
@Gfast2 For your use case, you need to change variable here and download css file
https://antdtheme.com

**Comment by Gfast2** [comment]
Hi @mzohaibqc : Thank you very much! I will invest some time on that repo! Have a nice day!

**Comment by afc163** [comment]
Seems that this issue had been fixed in https://github.com/mzohaibqc/antd-theme-generator/issues/27

**Comment by mzohaibqc** [comment]
@qizhancheng @afc163 There were some issues with box-shadow which I could not understand by reading this issue, totally my fault but before few days, I noticed random colors being generated for colors like `fade(@primary-color, 20%)` so now I've fixed this in https://github.com/mzohaibqc/antd-theme-webpack-plugin/issues/69

`antd-theme-generator@1.2.7` and `antd-theme-webpack-plugin@1.3.7` release fixed this issue. 

Dew to recent (at least for me) changes where ant design is using different variable for default and dark theme, it has become more difficult problem to produce `color.less` which handles both themes gracefully. However, `default` theme is supported out of the box completely but `dark` theme is not 100% supported out of the box but fixing few (two, three) issues for dark theme by adding  same variables with appropriate color for dark theme can fix this. Here is how I fixed date-picker  selecetd range color for dark theme
https://github.com/mzohaibqc/antd-theme-generator/blob/master/examples/customize-cra/color.js#L9


I am converting this package using Typescript (I am not typescreipt expert) so any kind of help is most welcome. I'm planning to merge both packages but both npm packages will contain core script as well as webpack plugin. This is to reduce the effort to maintain two code bases. 

Typescript conversion is in progress and any feedback and help is welcom. 
https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/typescript
