### ISSUE TITLE
select dropdown malfunctions when nested inside radio

### ISSUE THREAD

**Issue by kannagearing** [ant-design/ant-design#25959]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-clarke-dh6n3?file=/package.json:424-432)

### Steps to reproduce
1. choose a name in the select
2. choose another name in the same select

### What is expected?
In step 2, dropdown is retained and  we can type in select to choose a drop down option

### What is actually happening?
dropdown immediately disappears. We cannot type in select in step 2

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | ^16.12.0 |
| System | mac os |
| Browser | chrome  |

**Comment by afc163** [comment]
It works in Firefox.

**Comment by zombieJ** [comment]
Hmm.... Click on the radio make Select lost focus which close the popup.

**Comment by 07akioni** [comment]
> Hmm.... Click on the radio make Select lost focus which close the popup.

This could fixed by check whether `document.activeElement` exists inside radio async.

**Comment by kannagearing** [comment]
i am not familiar with antd implementation. Is there any plan to fix it in in the incoming releases?

**Comment by zombieJ** [comment]
wrap an stopPropagation tmp:  https://codesandbox.io/s/dazzling-currying-6d646?file=/index.js

**Comment by kannagearing** [comment]
@zombieJ  The solution does not seem to work. I can still see the problem when I type the name again in the select, in the url provided.

**Comment by lihqi** [comment]
try https://codesandbox.io/s/blissful-payne-wkxtn?file=/index.js

**Comment by kannagearing** [comment]
@lihqi  thanks. that works. Just curious if that additional span is just a workaround or your permeant solution (no intention to fix)?

**Comment by springHyc** [comment]
@lihqi 解决了，赞

**Comment by Chryseis** [comment]
> try https://codesandbox.io/s/blissful-payne-wkxtn?file=/index.js

when set it in form.item ,it losts value

**Comment by Chryseis** [comment]
> > try https://codesandbox.io/s/blissful-payne-wkxtn?file=/index.js
> 
> when set it in form.item ,it losts value

when set it out of form.item, it works well

**Comment by akateliev** [comment]
This is still an issue in November 2025 !

**Comment by afc163** [comment]
Thanks for the report. I retested the original selected-Radio structure on current master, including a Select controlled by a nested `Form.Item`. After the first selection, the form value is retained; the Select can then be reopened, typed into, and used to select another option without the popup disappearing.

The reported behavior no longer reproduces, so I am closing this as resolved. If a different case still occurs on current master, please open a new issue with a minimal reproduction showing the current conditions.
