### ISSUE TITLE
Less v4.0.0 Breaking Change with Parens

### ISSUE THREAD

**Issue by blujedis** [ant-design/ant-design#28427]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/releases/tag/4.9.4](https://github.com/ant-design/ant-design/releases/tag/4.9.4)

### Steps to reproduce
yarn install or npm install

### What is expected?
Version 4.0.0 of Less is installed which has a breaking change.

### What is actually happening?
Unrecognized input. Possibly missing '(' in mixin call. This happens due to a breaking change in version 4.x of Less that requires parens. See -> https://github.com/less/less.js/releases/tag/v4.0.0

| Environment | Info |
|---|---|
| antd | 4.9.4 |
| React | 16.x |
| System | OSX, Windows *Nix |
| Browser | any |

---
I installed Antd from scratch which installs the latest version of less which contains a breaking change that Antd less files do not appear to support.

**Comment by blujedis** [comment]
FYI Reverting to Less version 3.13.x seems to resolve the issue for now.

**Comment by sbue** [comment]
Having this issue too.

**Comment by qlchan24** [comment]
@blujedis Do you want to work on this issue? Otherwise I can try to fix this.

**Comment by blujedis** [comment]
@qlchan24 I won't be able to get to it for a few days so if you have time you are welcome to it.

**Comment by AFu-1993** [comment]
According to your description, I did not reproduce
``` sh
➜  ant-design git:(master) npm ls less
antd@4.9.4 /Users/huang/Hunter/repository/ant-design
├─┬ @ant-design/tools@11.0.5
│ └── less@3.13.1 
├─┬ antd-pro-merge-less@3.0.11
│ └── less@3.13.1  deduped
├─┬ antd-theme-generator@1.2.8
│ └── less@3.9.0 
└─┬ bisheng@2.0.0
  └── less@3.9.0 
```

**Comment by atzcl** [comment]
after less rolls back to 3.x version, it can work normally

**Comment by afc163** [comment]
Fixed in 28465

**Comment by afc163** [comment]
Still working in progress: https://github.com/ant-design/ant-design/pull/28466/

**Comment by Ulkeshwani** [comment]
This Issue Can be Fix if You roll Back less to @3.13.1 version

**Comment by Bac3Phi** [comment]
Same issue with Ant Design Vue when i used less ver 4.0

**Comment by shubhroshekhar** [comment]
> FYI Reverting to Less version 3.13.x seems to resolve the issue for now.

worked for me also

**Comment by chayakornjj** [comment]
Confirm on this issue, Temporary fixed by revert `less` back to version 3.xx

**Comment by javiersuzuki-ambiata** [comment]
@Ulkeshwani @shubhroshekhar @chayakornjj – how do you revert `less` to version 3.13.1?

**Comment by shubhroshekhar** [comment]
Yes

**Comment by mahmudipur** [comment]
hey guys!
here is my package.json and although I install less@3.13 , still doesn't work:
```
{
  "name": "client-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@zeit/next-less": "^1.0.1",
    "less": "3.13",
    "next": "11.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "rsuite": "^4.10.2"
  },
  "devDependencies": {
    "eslint": "7.30.0",
    "eslint-config-next": "11.0.1"
  }
}
```
after 'yarn dev' I have this error :
![Screenshot 2021-07-06 152432](https://user-images.githubusercontent.com/57182874/124589474-4973e400-de6f-11eb-8530-2b88401df217.png)
 can anyone help me
