### ISSUE TITLE
菜单收缩时，出现tooltip

### ISSUE THREAD

**Issue by 1zilc** [ant-design/ant-design#41081]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-undefined-forked-dffkh1?file=/demo.tsx)

### Steps to reproduce

1. 选中任意子菜单
2. 点击收缩菜单按钮

### What is expected?

1. 菜单收起后，无tooltip

### What is actually happening?

1. 菜单收起后，出现部分子菜单tooltip

### 截图
![image](https://user-images.githubusercontent.com/44715458/223045919-9c4ec460-9014-4725-adaa-4970197b16ad.png)

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18 |
| System | macos13 |
| Browser | chrome110 |

**Comment by MuxinFeng** [comment]
应该不是预期行为吧，我试试提个 pr~

**Comment by UmitKidly** [comment]
I have the same problem..

**Comment by afc163** [comment]
确实有问题。

**Comment by pchaganti** [comment]
+1

**Comment by pchaganti** [comment]
This bug can also be seen in the sample code on the Ant Design samples page - https://ant.design/components/layout

**Comment by LaiBaoYuan** [comment]
+1+1

**Comment by ZZZCNY** [comment]
+1，还有图标偏移的问题
![image](https://user-images.githubusercontent.com/59002875/224596985-2782a5a3-6fcd-4712-81a4-b8d3182f71c6.png)

**Comment by zombieJ** [comment]
fixed with `@rc-component/trigger`:
https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-undefined-forked-70zmpl

**Comment by bamtheboozle** [comment]
> fixed with `@rc-component/trigger`: [codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-undefined-forked-70zmpl](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-undefined-forked-70zmpl)

how exactly do we use this fix?

**Comment by ZZZCNY** [comment]
> > fixed with `@rc-component/trigger`: [codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-undefined-forked-70zmpl](https://codesandbox.io/s/suo-qi-nei-qian-cai-dan-antd-undefined-forked-70zmpl)
> 
> how exactly do we use this fix?

only update antd to 5.3.1

**Comment by youssefbrr** [comment]
I'm using antd version 5.3.1 but I still have the same problem

**Comment by yoyo837** [comment]
Try remove node_modules and lock file then reinstall it.

**Comment by afc163** [comment]
@peterleng 试试最新的 antd 版本
