### ISSUE TITLE
[TimePicker.RangePicker] Default behaviour has been changed and there is no prop to configure it

### ISSUE THREAD

**Issue by linkfang** [ant-design/ant-design#44724]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/time-range-picker-antd-5-9-0-forked-glcnfw?file=/demo.tsx)

### Steps to reproduce

Choose any hour then the minute and second will be automatically synced up with current time.

### What is expected?

Previously, after choose hour, the minute and second will stay as `00`. In my use case, this would be better. Because it's easier for the user to select a desired range (e.g., 3:00:00 to 7:00:00).
v5.3.2 code sandbox: https://codesandbox.io/s/time-range-picker-antd-5-9-0-forked-4y6dw9?file=/index.tsx

If this change is intended, is it possible to provide a prop to configure this behaviour? 
And I personally think it might be better to keep the default behaviour same as before and offer the new prop for developers to change it when needed. 
In this case, updating AntD version will not change the behaviour of an existing app.

### What is actually happening?

Choose any hour first, then the minute and second will be automatically synced up with current time. And this will make it harder for the user to choose a desired time range(e.g., 3:00:00 to 7:00:00, or 3:30:00 to 7:30:00)

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | Mac OS |
| Browser | Edge |

**Comment by linkfang** [comment]
Hi @MadCcc , I am not sure if removing the `Documentation` label was intended? 
It's been 3 weeks, will this be fixed in future releases or regarded as a non-issue? Thanks! 😊

**Comment by letsevi** [comment]
`v5.9.0`
I'm facing the same problem. This greatly impacts our UX 😞

**Comment by zombieJ** [comment]
Original can use `showTime.defaultValue` to handle this. But seems a bug not working.

**Comment by spoilerdo** [comment]
In our software this bug shows up whenever we use version **5.3.0**. So currently we are stuck on version 5.2.0

**Comment by spoilerdo** [comment]
This issue is still not fixed, even with the new version. The problem only occurs inside the TimePicker.RangePicker

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
