### ISSUE TITLE
Menu "theme" prop does not have effect inside of a dropdown

### ISSUE THREAD

**Issue by tim-richter** [ant-design/ant-design#45549]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/menu-dark-inside-dropdown-c6rnrz)

### Steps to reproduce

1. Use menu inside a dropdown via 'menu' prop
2. Set 'theme=dark' inside of the menu prop

### What is expected?

The menu should be dark themed

### What is actually happening?

The menu styling is exactly as with the light theme

| Environment | Info |
| --- | --- |
| antd | 5.10.2 |
| React | 18 |
| System | NixOS |
| Browser | Chrome Version 116.0.5845.179 (Official Build) (64-bit) |

**Comment by MadCcc** [comment]
We haven't make this yet, and do not have plan to support it.
Maybe we should fix typescript defination.

**Comment by tim-richter** [comment]
@MadCcc thanks for the fast answer!

It worked in antd v4 so I'm not entirely sure, why this is not possible in antd v5. Seems like a regression to me.

Otherwise yeah, removing that theme prop would be a start, but you can still render a menu inside of 'dropdownRender', with dark theme enabled, and it still wouldn't work, because the css from the dropdown basically overwrites anything that comes from the menu itself. So if this is not supposed to work anymore in v5, it would be better to have it as a FAQ on the page, so people don't run into this by accident, imo.

**Comment by MadCcc** [comment]
Just checked in v4 and it worked. We should fix this.

**Comment by buwyi** [comment]
Here's the English translation you can use to respond in a GitHub issue:

---

I encountered the same issue with Ant Design version 5.24.5. Setting `theme="dark"` in the `menu` prop of the `Dropdown` component has no effect. I also tried using the `dropdownRender` prop to render a `Menu` component directly, but the dark theme still doesn't take effect. Is there a recommended solution for this?

**Comment by buwyi** [comment]
I encountered the same issue with Ant Design version 5.24.5. Setting `theme="dark"` in the `menu` prop of the `Dropdown` component has no effect. I also tried using the `dropdownRender` prop to render a `Menu` component directly, but the dark theme still doesn't take effect. Is there a recommended solution for this?

**Comment by afc163** [comment]
Reviewed against the latest `master` (`0b1021909f`). Dropdown now applies the dark Menu theme supplied through menu.theme.

Latest master commit 9f6fabf2e4 added the style handling and regression test and explicitly closes #45549.

Closing this issue accordingly. If a minimal reproduction still demonstrates different behavior on the current `master`, please open a new issue with that reproduction.
