### ISSUE TITLE
ref errors occur when working with React v19

### ISSUE THREAD

**Issue by Alperec** [ant-design/ant-design#51940]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/react-v19-ref-errors-89hvvt?file=%2Findex.tsx%3A12%2C6&workspaceId=ws_Wz7JZVzeXmn9ZRAMzGL2fS)

### Steps to reproduce

open the console and see the error

### What is expected?

error related to ref does not occur

### What is actually happening?

there are a lot of errors

| Environment | Info |
| --- | --- |
| antd | 5.22.3 |
| React | 19.0.0 |
| System | Windows 10 |
| Browser | Chrome 131.0.6778.109 |

**Comment by Alperec** [comment]
Additionally, when calling antd components, this error occurs: Cannot update a component (`HotReload`) while rendering a different component (`Wave`). To locate the bad setState() call inside `Wave`, follow the stack trace as described in https://react.dev/link/setstate-in-render Error Component Stack

**Comment by 18396461958** [comment]
啥时候能适配上 用的很难受

**Comment by dgtllion** [comment]
I get also this error even with updated `wave/index.js`
Versions: 
antd 5.22.4
Nextjs: 15.1.0

![Screenshot 2024-12-12 at 06 19 36](https://github.com/user-attachments/assets/f3f46dc8-cff2-4e13-a430-ae169c21e923)

**Comment by dgtllion** [comment]
i use a patch as a workaround.

**Comment by whatdfjslfjldks** [comment]
I downgraded the Next.js version to 14, and it seems that Ant Design made ref compatibility adjustments for version 15.

**Comment by dgtllion** [comment]
The error with wave is fixed with `antd: 5.22.5` version

**Comment by whatdfjslfjldks** [comment]
> The error with wave is fixed with `antd: 5.22.5` version

Thx,I'll try it later

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/51952

**Comment by carlosmca44** [comment]
The error with wave still occurs:

* antd 5.22.5
* Nextjs: 15.1.2
* ReactJs 19

I'm using wave={{ disabled: true }} in the ConfigProvider to prevent the error, but this is not a solution

![wave_error](https://github.com/user-attachments/assets/b208b3cb-cf63-4adf-8cdf-0ec928106afd)
