### ISSUE TITLE
Component deprecation warning due to React upgrading to v15.5.0

### ISSUE THREAD

**Issue by mdluo** [ant-design/ant-design#5678]
### Version
2.9.1

### Environment
Chrome 56

### Reproduction link
[http://codepen.io/benjycui/pen/KgPZrE](http://codepen.io/benjycui/pen/KgPZrE)

### Steps to reproduce
N.A.

### What is expected?
No such warning messages

### What is actually happening?
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

`Warning: AnimateChild: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

---
https://github.com/facebook/react/releases/tag/v15.5.0

**Comment by afc163** [comment]
Happen earlier than we expect: #5377

**Comment by afc163** [comment]
https://www.npmjs.com/package/create-react-class

**Comment by igor-lemon** [comment]
+1

**Comment by afc163** [comment]
- [ ] https://github.com/react-component/collapse/pull/58

**Comment by yesmeck** [comment]
`prop-types` doesn't work with react under 15.3.0.  If we introduce `prop-types`, that means `antd` must dependent react 15.3.0+;

**Comment by afc163** [comment]
> prop-types doesn't work with react under 15.3.0

What's the problem?

**Comment by yesmeck** [comment]
See https://github.com/yesmeck/test-prop-types

**Comment by afc163** [comment]
```
"Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types
    in Unknown (created by Component)
    in Component"
```

**Comment by afc163** [comment]
I think it is OK, there is no reason to stay in `react@15.1` or `react@15.2`.

**Comment by yesmeck** [comment]
Should we add `"react": "^15.5.0"` to `peerDependencies` as `prop-types` recommend https://github.com/reactjs/prop-types#how-to-depend-on-this-package?

**Comment by paranoidjk** [comment]
rc-slider 7.0.1
rc-checkbox 2.0.0

**Comment by vauruk** [comment]
I find this information, for react 15.5.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by ddcat1115** [comment]
`react-lazy-load` trace this [issue](https://github.com/loktar00/react-lazy-load/issues/90)

**Comment by ddcat1115** [comment]
`react-slick` update to `0.14.11`

**Comment by aztack** [comment]
Is antd@2.9.2 ready for react@15.5.0 now(2017-04-24)?

**Comment by whx76** [comment]
BreadcrumbItem prop-types   Warning
create-react-class Notice  Warning

**Comment by afc163** [comment]
- [ ] https://github.com/ant-design/ant-design/blob/4951df182be5642d3387ee6b681cd581e9ce42f0/components/form/Form.tsx#L123

@benjycui

**Comment by NamitYadav** [comment]
Please update rc-notification to 1.4.2(latest).

**Comment by paranoidjk** [comment]
@NamitYadav No need to upgrade, https://github.com/ant-design/ant-design/blob/master/package.json#L57, just reinstall your node modules.

**Comment by vagusX** [comment]
so when will it release?

**Comment by artem-ovcharenko-codilime** [comment]
Hello guys, DatePicker component throws warning:

> Warning: DateTBody: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

could you fix pls.

**Comment by 422563261** [comment]
How to solve the problem?

**Comment by 39Er** [comment]
Until now, I find there are also  lots of warnings , for example in rc-form and rc-select.Except for using 
react v15.4, when will antd support v15.5 without warnings? It seems like a huge change...

**Comment by gaearon** [comment]
Please see https://github.com/reactjs/prop-types/issues/38.

This was a false positive caused by production version of `prop-types` generating a mistaken warning when development version of React is calling it.

**It is fixed in `prop-types@15.5.10`.**

You might need to rebuild the UMD bundle of the component that depends on `prop-types` (probably this repo) to see the changes.

**Comment by afc163** [comment]
I believe all warnings are fixed in master, which will be released in this week: `1.10.2`. :tada:

**Comment by enzolutions** [comment]
@afc163 you mean 2.10.2 📦

**Comment by qq645381995** [comment]
天天等着这个  就怕这周改不完 发不了版  那得等到下周五了

**Comment by afc163** [comment]
2.10.2 is released!

**Comment by pleunv** [comment]
For some reason `yarn` is still getting `rc-switch@1.4.3` after an install/upgrade, any idea why?

**Comment by 39Er** [comment]
update to 2.10.2,but there's still two warnings:

1.   warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them.

2. Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead. 

In my project,I only use antd and react-router v4 which are related to react,what's the problem?

**Comment by krszwsk** [comment]
I also updated to 2.10.2 and I keep getting this error:

Warning: Form: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by afc163** [comment]
Try `yarn upgrade`?

**Comment by butfunny** [comment]
i updated to 2.10.2 and getting this error: 
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by krszwsk** [comment]
@afc163 Thanks, that fixed it.

**Comment by zhulinpinyu** [comment]
I have tried `yarn upgrade`,  also got same warning. `antd 2.10.2` `react 15.5.4`

**Comment by benjycui** [comment]
@zhulinpinyu could you try to find out the component which had printed this warning? Thanks.

**Comment by qq645381995** [comment]
引用的组件太多，可能是别的组件报的错误。
react-router 如果用 2.X  会有React.createClass 报错 
react-router 如果用 3,x 就没有 React.createClass   但是还是会有  prop-types 报错
但是这个错误 到底是哪个组件的错误 就不知道了

**Comment by 39Er** [comment]
can someone tell me why I got those two warnings in my previous comment?

**Comment by qq645381995** [comment]
The problem of other plug-ins, with screening and see which plug-in version is low
