### ISSUE TITLE
React 16 Warning: Received `true` for non-boolean attribute `unselectable`.

### ISSUE THREAD

**Issue by violabg** [ant-design/ant-design#7798]
### Version
2.13.4

### Environment
browser

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
Upgrade to React 16 and use a TreeSelect with this properties:

``` javascript
const tProps = {
    multiple: true,
    treeData,
    treeCheckable: true,
    showCheckedStrategy: SHOW_PARENT,
    searchPlaceholder: "Select one or more Categories",
    filterTreeNode: filterCategories,
    allowClear: true
  };
  return (
    <TreeSelect
      className="search-panel-element"
      {...tProps}
      value={selectedCategories}
      onChange={onSelectCategory}
      getPopupContainer={triggerNode => triggerNode.parentNode}
    />
  );

```

### What is expected?
no warnings

### What is actually happening?
receiving warnings:
```
Warning: Received `true` for non-boolean attribute `unselectable`. If this is expected, cast the value to a string.
in ul (created by Tree)
in Tree (created by SelectTrigger)
in div (created by SelectTrigger)
in LazyRenderBox (created by PopupInner)
in div (created by PopupInner)
in PopupInner (created by Popup)
in Align (created by Popup)
in AnimateChild (created by Animate)
in Animate (created by Popup)
in div (created by Popup)
in Popup
```

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tree/pull/131

**Comment by hengkx** [comment]
antd 3.1.0

warning still exists

**Comment by hengkx** [comment]
```
Warning: Received `true` for a non-boolean attribute `unselectable`.

If you want to write it to the DOM, pass a string instead: unselectable="true" or unselectable={value.toString()}.
    in ul (created by Tree)
    in Tree (created by SelectTrigger)
    in div (created by SelectTrigger)
    in LazyRenderBox (created by PopupInner)
    in div (created by PopupInner)
    in PopupInner (created by Popup)
    in Align (created by Popup)
    in AnimateChild (created by Animate)
    in Animate (created by Popup)
    in div (created by Popup)
    in Popup (created by Trigger)
    in Portal (created by Trigger)
    in Trigger (created by SelectTrigger)
    in SelectTrigger (created by Select)
    in Select (created by LocaleReceiver)
    in LocaleReceiver (created by TreeSelect)
    in TreeSelect (created by WriteBasicInfo)
    in div (created by FormItem)
    in div (created by Col)
    in Col (created by FormItem)
    in div (created by Row)
    in Row (created by FormItem)
    in FormItem (created by WriteBasicInfo)
    in div (created by WriteBasicInfo)
    in form (created by Form)
    in Form (created by WriteBasicInfo)
    in div (created by WriteBasicInfo)
    in WriteBasicInfo (created by Connect(WriteBasicInfo))
    in Connect(WriteBasicInfo) (created by Form(Connect(WriteBasicInfo)))
    in Form(Connect(WriteBasicInfo)) (created by ComponentCreate)
    in div (created by ComponentCreate)
    in div (created by ComponentCreate)
    in ComponentCreate (created by Dashboard)
    in div (created by Motion)
    in div (created by Motion)
    in Motion (created by Mortal)
    in Portal (created by Mortal)
    in Mortal (created by Panel)
    in Panel (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by Connect(Dashboard))
    in Connect(Dashboard) (created by Route)
    in Route (created by withRouter(Connect(Dashboard)))
    in withRouter(Connect(Dashboard)) (created by Route)
    in Route (created by Main)
    in Switch (created by Main)
    in div (created by Main)
    in Main (created by Route)
    in Route (created by withRouter(Main))
    in withRouter(Main) (created by Route)
    in Route
    in Switch
    in Router
    in Provider
    in Unknown
```

**Comment by hengkx** [comment]
antd use rc-tree `~1.7.0`. but rc-tree `1.7.5` fixed. 
Please upgrade rc-tree.
The local cached version is old.

**Comment by shahzeb1** [comment]
I'm still getting the same error but with `<Checkbox />`.

Is there a fix for this?

**Comment by wangmeijian** [comment]
antd 3.2.2
react 16.2.0

warning still exists
upgrade rc-tree fixed

**Comment by dilee716** [comment]
I'm getting similar error with `<Dropdown />`.

`Warning: Received `false` for a non-boolean attribute `selectable`.`

**Comment by lvlohammadi** [comment]
Same here for `<Dropdown>`.
```
  console.error node_modules/fbjs/lib/warning.js:33
    Warning: Received `false` for a non-boolean attribute `selectable`.

    If you want to write it to the DOM, pass a string instead: selectable="false" or selectable={value.toString()}.

    If you used to conditionally omit it with selectable={condition && value}, pass selectable={condition ? value : undefined} instead.
        in div (created by UserDetailDropDown)
        in LazyRenderBox (created by PopupInner)
        in div (created by PopupInner)
        in PopupInner (created by Popup)
        in Align (created by Popup)
        in AnimateChild (created by Animate)
        in Animate (created by Popup)
        in div (created by Popup)
        in Popup (created by Trigger)
        in Portal (created by Trigger)
        in Trigger (created by Dropdown)
        in Dropdown (created by Dropdown)
        in Dropdown (created by UserDetailDropDown)
        in span (created by UserDetailDropDown)
        in UserDetailDropDown (created by Route)
        in Route (created by withRouter(UserDetailDropDown))
        in withRouter(UserDetailDropDown) (created by Mutation)
        in Mutation (created by Apollo(withRouter(UserDetailDropDown)))
        in Apollo(withRouter(UserDetailDropDown)) (created by Query)
        in Query (created by Apollo(Apollo(withRouter(UserDetailDropDown))))
        in Apollo(Apollo(withRouter(UserDetailDropDown)))
        in Router
        in ApolloProvider (created by MockedProvider)
        in MockedProvider (created by MockedProvider)
        in MockedProvider (created by WrapperComponent)
        in WrapperComponent
```

**Comment by NgeKaworu** [comment]
`<Select> `

```

Warning: Received `true` for a non-boolean attribute `right`.

If you want to write it to the DOM, pass a string instead: right="true" or right={value.toString()}.
    in li (created by MenuItem)
    in MenuItem (created by Connect(MenuItem))
    in Connect(MenuItem) (created by MenuItem)
    in Trigger (created by Tooltip)
    in Tooltip (created by Tooltip)
    in Tooltip (created by MenuItem)
    in MenuItem (created by Header)
    in ul (created by DOMWrap)
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by Menu)
    in Provider (created by Menu)
    in Menu (created by Menu)
    in Menu (created by Header)
    in div (created by Col)
    in Col (created by Header)
    in div (created by Row)
    in Row (created by Header)
    in Header (created by Connect(Header))
    in Connect(Header) (created by Layout)
    in div (created by Layout)
    in LocaleProvider (created by Layout)
    in Layout (created by Route)
    in Route (created by withRouter(Layout))
    in withRouter(Layout) (created by Route)
    in Route (created by Route)
    in Switch (created by Route)
    in Route
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Unknown
    in Provider (created by DvaContainer)
    in DvaContainer

```

**Comment by hernimen** [comment]
same in table

**Comment by afc163** [comment]
Please create new issue with reproducible codesandbox if you guys meet same problem.

**Comment by lvlohammadi** [comment]
@afc163 It seems we encountered this error because of this line (https://github.com/ant-design/ant-design/blob/master/components/dropdown/dropdown.tsx#L65).
> menu cannot be selectable in dropdown defaultly

So if someone puts `menu` inside a `div`, It will break down.
I think that's the same problem for rest of the guys.
Sorry to go on this issue.

**Comment by ShandelleLovato** [comment]
I had the same issue, and it was solved by getting rid of all my html div tags and replacing them with Segment or Fragment, for some reason it seems to matter now and didn't when I project last open a couple of weeks ago.  It looks like React doesn't like it when I was mixing `<div>` with React or Semantic components?
Causes errors: 
`<div>
  <Component>
  </Component>
</div>`
Doesn't cause errors: 
`<Fragment>
  <Component>
  </Component>
</Fragment>`

**Comment by FgoPan** [comment]
any solution?

**Comment by leckman** [comment]
Also having this problem with Buttons inside a Popover: https://codesandbox.io/s/92ym2k9xrw?module=%2Fsrc%2Findex.js

**Comment by zombieJ** [comment]
@leckman , remove `block` prop: https://codesandbox.io/s/vj369ox1nl

**Comment by leckman** [comment]
@zombieJ I understand that the `block` prop is causing the error, however it is [listed as a supported property in the documentation](https://ant.design/components/button/#components-button-demo-block) and I specifically want to use it in this case. I reported the issue here because the `block` property is not working as described/expected and the error seems similar to those above, but  if this is outside the scope of the original ticket I'm happy to file a separate issue.

**Comment by zombieJ** [comment]
@leckman , `block` not exist in `antd@3.5.2`: https://codesandbox.io/s/v3j5lnxrn3

**Comment by tiarebalbi** [comment]
This is a known issue on https://github.com/styled-components/styled-components/issues/1198

**Comment by Hugofv** [comment]
test this.
[https://github.com/styled-components/styled-components/issues/1198](url)

**Comment by 378840826** [comment]
在报错的组件外包一层div能暂时解决报错
