### ISSUE TITLE
List with empty dataSource & loading shows spinner and "No data"

### ISSUE THREAD

**Issue by Ehesp** [ant-design/ant-design#8788]
### Version
3.0.3

### Environment
N/A

### Reproduction link
[https://codesandbox.io/s/03lv05vxjl](https://codesandbox.io/s/03lv05vxjl)

### Steps to reproduce
```
<List
      itemLayout="vertical"
      dataSource={[]}
      loading
    />
```

### What is expected?
Only the spinner should show.

### What is actually happening?
The spinner shows above the "No data" text. The text should only show when loading is false.

![image](https://user-images.githubusercontent.com/842078/34438918-25e9e8c6-eca2-11e7-958f-166483dd1843.png)

**Comment by yesmeck** [comment]
@Ehesp Fixed in 3.1.0

**Comment by yesmeck** [comment]
@yutingzhao1991 Need add this to change log

**Comment by ilyaLibin** [comment]
@yesmeck Is it a way to change the default placeholder of "No Data"?

**Comment by ncknuna** [comment]
@yesmeck 

It looks like there are two issues being reported here:
1. The spinner is displaying on top of the text. This has been fixed
2. The text shouldn't show if the spinner is showing. This is still happening in 3.1.3 (https://codepen.io/anon/pen/OzdLrR?editors=0010). 

Is #2 considered working as intended, and both the spinner and the "No data" text should be shown?

**Comment by yesmeck** [comment]
@ncknuna Can you open a separate issue?

**Comment by ncknuna** [comment]
https://github.com/ant-design/ant-design/issues/9069
